uvt_edu/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.base import TemplateView, RedirectView
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',

      url(r'^$', 'uvt.views.index'),
      url(r'^blog/', include('articles.urls')),
      url(r'^artikel/$', 'uvt.views.artikel'),
      url(r'^tutorial/$', 'uvt.views.tutorial'),
      url(r'^aplikasi/$', 'uvt.views.aplikasi'),
      url(r'^kategori/$', 'uvt.views.kategori'),
      url(r'^jadwal/$', 'uvt.views.jadwal'),
      url(r'^pastebin/', include('pastebin.urls')),
      url(r'^kontak/$', 'uvt.views.kontak'),
      url(r'^thanks/$', 'uvt.views.kontak'),
      url(r'^accounts/', include('registration.backends.default.urls')),
      url(r'^', include('perpustakaan.urls')),
      url(r'^tinymce/', include('tinymce.urls')),
      url(r'^admin/', include(admin.site.urls)),
      url(r'live/', include('live.urls')),
      url(r'^media/(?P<path>.*)', 'django.views.static.serve', {'document_root': 'media'}),
      url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico')),
      url(r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'index.html'}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
   )

uvt/models.py
import django
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
from django import forms
from django.forms import ModelForm


class Post(models.Model):	
    penulis = models.ForeignKey(User)
    judul = models.CharField(max_length=200)
    body = tinymce_models.HTMLField("tulisan")
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
		ordering = ['penulis', 'judul', 'body']
		verbose_name_plural = "Post"
	
    def __unicode__(self):
		return self.judul
		
class Kategori_Perpus(models.Model):
	kategori = models.CharField(max_length=30)
	jenis_buku = models.CharField(max_length=30)
	
	class Meta:
		verbose_name_plural = "Kategori_Perpustakaan"
		
	def __unicode__(self):
		return self.kategori
	
class Buku(models.Model):
	judul = models.CharField(max_length=100)
	penulis = models.CharField(max_length=100)
	kategori = models.ForeignKey(Kategori_Perpus)
	cover = models.ImageField(upload_to="media/images", blank=True, null=True)
	tentang = tinymce_models.HTMLField("Deskripsi")
	penerbit = models.CharField(max_length=50)
	tanggal_publikasi = models.DateField()
	
	class Meta:
		verbose_name_plural = "Buku"
	
	def __unicode__(self):
		return self.judul


class Kategori_App(models.Model):
    nama = models.CharField(max_length=50, unique=True)
    deskripsi = models.TextField(default='', blank=True)
    ordering = models.IntegerField(default=0)

    def __unicode__(self):
        return self.nama

    class Meta:
        ordering = ('ordering',)
        verbose_name_plural = 'Kategori_Aplikasi'

class Aplikasi(models.Model):
    kategori = models.ForeignKey('categories.Category')
    nama = models.CharField(max_length=50, unique=True)
    developer = models.CharField(max_length=50, unique=True)
    deskripsi = models.TextField(default='', blank=True)
    url = models.URLField(verify_exists=False, null=True, blank=True)
    tanggal = models.DateField()
    ordering = models.IntegerField(default=0)

    def __unicode__(self):
        return self.nama

    class Meta:
        ordering = ('developer', 'ordering',)
        verbose_name_plural = 'Aplikasi'
        
       
class KontakForm(forms.Form):
	subjek = forms.CharField()
	pesan = forms.CharField()
	pengirim = forms.EmailField()
	cc_myself = forms.BooleanField(required=False)
	
	class Meta:
		verbose_name_plural = "Kontak"
	
	def __unicode__(self):
		return self.subjek
	
class Jadwal(models.Model):
	hari = models.CharField(max_length=50)
	jam = models.TimeField("Waktu")
	tanggal = models.DateField()
	materi = models.TextField("Materi Kuliah")
	dosen = models.CharField(max_length=100)
	keterangan = models.TextField()
	
	class Meta:
		verbose_name_plural = "Jadwal"
	
	def __unicode__(self):
		return self.hari

templates/aplikasi.html
{% extends "base.html" %}

{% block content %}

<h1> Kumpulan Aplikasi Python</h1>


{% endblock %}

templates/artikel.html
{% extends "base.html" %}
{% load article_tags %}



{% block content %}
	   <h1>Artikel terakhir</h1>
        {% get_articles 10 as recent %}
        {% for article in recent %}
        {% if forloop.first %}<ul>{% endif %}
            <li><a href="{{ article.get_absolute_url }}" title="Read this article">{{ article.title }}</a></li>
        {% if forloop.last %}</ul>{% endif %}
        {% endfor %}
    </li>
    {% endblock %}

    {% block article_tags %}
    <li>
        <h2>Tag Cloud</h2>
        {% tag_cloud %}
    </li>
    {% endblock %}
    
    {% block footer %}
<p>Copyright &copy; {% now "Y" %} Me. All rights reserved.</p>
{% endblock %}

templates/contact_us.html
{% extends "base.html" %}
{% block content %}

<!-- START LEFT-SIDE CONTACT FORM AREA -->                        
                            <div class="contact-form span8">
                                <h1>Contact Us</h1>
                                <form id="validForm">
                                    {{ form.non_field_errors }}
                                        <div class="control-group">
                                            {{ form.subjek.errors }}
                                            <label class="control-label" for="id_subject">Subjek<sup>*</sup></label>
                                            <div class="controls">
                                                <input type="text" class="span4" id="id_subjek" placeholder="Name">
												<span class="help-inline">Masukan Subjek</span>
					      {{ form.subjek }}
                                            </div> 
                                            
                                        </div>                                         
                                        <div class="control-group">
                                           {{ form.pengirim.errors }}
                                            <label class="control-label" for="inputEmail">SUREL<sup>*</sup></label>
                                            <div class="controls">
                                                <input type="text" class="span4" id="inputEmail" placeholder="Email">
                                                <span class="help-inline">Masukkan Email dengan Benar</span>
                                                 {{ form.pesan }}
                                            </div>
                                        </div>                                        
                                        <div class="control-group">
                                         {{ form.pengirim.errors }}
                                            <label for="textarea" class="control-label">PESAN<sup>*</sup></label>
                                            <div class="controls">
                                                <textarea rows="4" class="span8" id="textarea"></textarea>
												<span class="help-inline">Silakan Tulis Pesan</span>
					 {{ form.pesan }}
                                            </div>
                                        </div>
                                        <div class="control-group form-button-offset">
                                            <input type="submit" class="btn" value="Send Message" />
                                        </div>
                                    </form> 
                                                      <ul class="errorlist">
    <li>Sender is required.</li>
</ul>
{% if form.subject.errors %}
    <ol>
    {% for error in form.subjek.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}
{% endblock %}             
                                </div>
<!-- END LEFT-SIDE CONTACT FORM AREA -->

<!-- BEGIN RIGHT-SIDE CONTACT FORM AREA -->
                                <div class="contact-info span4">
                                    <h2>bizstrap</h2>
<!-- COMPANY ADDRESS -->                                    
                                    <address>
                                        1234 Main Street,<br />
                                        Anytown,<br />
                                        USA<br />
                                        Phone: 123 456 7890<br />
                                        Fax: +49 123 456 7891<br />
                                        Email: <a href="mailto:hello@example.com">hello@example.com</a><br />
                                        Web: <a href="#">example.com</a>
                                    </address>
<!-- SOCIAL ICONS -->                                                                
                                    <ul class="socials unstyled">
                                        <li><a href="#" class="flickr"></a></li>
                                        <li><a href="#" class="twitter"></a></li>
                                        <li><a href="#" class="facebook"></a></li>
                                        <li><a href="#" class="youtube"></a></li>
                                        <li><a href="#" class="dribbble"></a></li>
                                        <li><a href="#" class="pinterest"></a></li>
                                    </ul>
<!-- HOURS OF OPERATION -->                                    
                                    <h2>Hours of Business Operation</h2>
                                        <table class="table">
                                        <tbody>
                                            <tr>
                                                <td class="small">Monday:</td>
                                                <td class="bold">8am to 6pm</td>
                                            </tr>
                                            <tr>
                                                <td class="small">Tuesday:</td>
                                                <td class="bold">8am to 6pm</td>
                                            </tr>
                                            <tr>
                                                <td class="small">Wednesday:</td>
                                                <td class="bold">8am to 6pm</td>
                                            </tr>
                                            <tr>
                                                <td class="small">Thursday:</td>
                                                <td class="bold">8am to 6pm</td>
                                            </tr>
                                            <tr>
                                                <td class="small">Friday:</td>
                                                <td class="bold">8am to 6pm</td>
                                            </tr>
                                            <tr>
                                                <td class="small">Saturday:</td>
                                                <td>Closed</td>
                                            </tr>
                                            <tr>
                                                <td class="small">Sunday:</td>
                                                <td>Closed</td>
                                            </tr>
                                        </tbody>
                                        </table>
                                </div>
<!-- END RIGHT-SIDE CONTACT FORM AREA -->

<!-- GOOGLE MAP -->                                
<iframe style="width: 100%; height: 600px; border: none;" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Mockingbird+Station,+Dallas,+TX&amp;aq=1&amp;oq=mockinStation,+Dallas,+TX&amp;sll=32.786144,-96.788897&amp;sspn=0.00929,0.018947&amp;ie=UTF8&amp;hq=&amp;hnear=Mockingbird+Station,+Dallas,+Texas+75206&amp;t=m&amp;ll=32.845774,-96.772385&amp;spn=0.043266,0.061712&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Mockingbird+Station,+Dallas,+TX&amp;aq=1&amp;oq=mockinStation,+Dallas,+TX&amp;sll=32.786144,-96.788897&amp;sspn=0.00929,0.018947&amp;ie=UTF8&amp;hq=&amp;hnear=Mockingbird+Station,+Dallas,+Texas+75206&amp;t=m&amp;ll=32.845774,-96.772385&amp;spn=0.043266,0.061712&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small>
                        </div>               
                    </div>
                    </div>
                </div>
                <hr>


templates/jadwal.html
{% extends "base.html" %}
{% block content %}
	<div class="container">
	        <div class="hero-unit">
        <h3>JADWAL KULIAH PEMOGRAMAN PYTHON ONLINE UNIVERSITAS VIRTUAL TERBUKA</h3><hr>	          
            
	            <div class="table-hover">
	              <div class="table">
                        	            
	            <table>
	                <tbody>
	                    <tr>
	                        <th>No</th>
	                        <th>Hari</th>
	                        <th>Jam</th>
	                        <th>Bulan-Tanggal-Tahun</th>
	                        <th>Materi</th>
	                        <th>Dosen</th>
	                        <th>Keterangan</th>
	                    </tr>    
	                </tbody>
	                    {% for jadwal in jadwal %}          
	                        <tr>
	                            <td>{{ jadwal.id }}</td>
	                            <td>{{ jadwal.hari }}</td>
	                            <td>{{ jadwal.jam }}</td>
	                            <td>{{ jadwal.tanggal }}</td>
	                            <td>{{ jadwal.materi }}</td>
	                            <td>{{ jadwal.dosen }}</td>
	                            <td>{{ jadwal.keterangan }}</td>
	                            
	                        </tr>     
                        {% endfor %}
                        
                </table>
	        </div>
	        </div>
                
	</div>
	    		

{% endblock %}

  

templates/kontak.html
{% extends "base.html" %}

{% block content %}
<h2>kontak</h2>

<form action="/kontak/" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.subjek.errors }}
        <label for="id_subject">Subjek Surel:</label>
        {{ form.subjek }}
    </div>
    <div class="fieldWrapper">
        {{ form.pesan.errors }}
        <label for="id_message">Pesan:</label>
        {{ form.pesan }}
    </div>
    <div class="fieldWrapper">
        {{ form.pengirim.errors }}
        <label for="id_sender">Alamat Surel:</label>
        {{ form.pengirim }}
    </div>
    <div class="fieldWrapper">
        {{ form.cc_myself.errors }}
        <label for="id_cc_myself">CC yourself?</label>
        {{ form.cc_myself }}
    </div>
    <p><input type="submit" value="Kirim Pesan" /></p>
</form>

<ul class="errorlist">
    <li>Sender is required.</li>
</ul>
{% if form.subject.errors %}
    <ol>
    {% for error in form.subjek.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}
{% endblock %}

templates/list.html
{% extends "base.html" %}
{% load comments %}
{% load tinymce_tags %}
{% block content %}

<div class="resources">
	        <div class="resources">
	        <h3> Artikel Tentang Programming Python</h3>
	  
           <!-- Posts  -->
        <ul>
            {% for post in posts.object_list %}
                <div class="title"><h2>{{ post.judul }}</h2></div>
                <ul>
                    <div class="time">{{ post.created }}</div>
                    <div class="body">{{ post.body|linebreaks }}</div>
                </ul>
            {% endfor %}
        </ul>
	
              
        <!-- Next/Prev page links  -->
        {% if posts.object_list and posts.paginator.num_pages > 1 %}
        <div class="pagination" style="margin-top: 20px; margin-left: -20px; ">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href= "?page={{ posts.previous_page_number }}">Postingan Baru &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}"> &gt;&gt; Postingan Lama</a>
                {% endif %}
            </span>
        </div>
        {% endif %}

    </div>

{% endblock %}

templates/perputakaan.html
{% extends "base.html" %}
{% load pagination_tags %}
{% block content %}

<h2><center>Perpustakaan Universitas Virtual Indonesia</center></h2>
<hr>
{% for perpus in perpustakaan.object_list %}
<div id="content" class="clearfix">
		<section id="left">
			<div id="userStats" class="clearfix">
				<div class="pic">
					<a href="#"><img src="{{ perpus.cover}}" width="150" height="150" /></a>
				</div>
				
				<div class="data">
					<h2>{{ perpus.judul }}</h2>
					<h2>{{ perpus.penulis }}</h2>
					<h3>Kategori Buku</h3>
					<p>{{ perpus.kategori }}</p>
					<p>{{ perpus.tanggal_publikasi }}</p>
				</ul>
				</div>
			<h2>Keterangan:</h2>
			<p>{{ perpus.tentang|linebreaks }}</p>
		</section>
		</div>
{% endfor %}

{% if perpustakaan.has_previous %}
<div class="pagination" style="margin-top: 20px; margin-left: -20px; ">
            <span class="step-links">
   <a href="?page={{ insurance_perpustakaan.previous_page_number }}">sebelumnya</a>
{% endif %}

{% for num in insurance_perpustakaan.paginator.page_range %}
    {% ifequal num insurance_perpustakaan.number %}
        <span class="current page">{{ num }}</span>
    {% else %}
        <a href="?page={{ num }}"> {{ num }}</a>
    {% endifequal %} 
{% endfor %}
    
{% if insurance_perpustakaan.has_next %}
    <a href="?page={{ insurance_perpustakaan.next_page_number }}"> Selanjutnya</a>
{% endif %}
     </span>
       

{% endblock %}

templates/post.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	        <div class="hero-unit">
	        <h2> </h2>
<!-- Comments  -->
{% if comments %}
    <p>Comments:</p>
{% endif %}

{% for comment in comments %}
    <div class="comment">
        <div class="time">{{ comment.created }} | {{ comment.author }}</div>
        <div class="body">{{ comment.body|linebreaks }}</div>
    </div>
{% endfor %}

<div id="addc">Add a comment</div>
<!-- Comment form  -->
<form action="{% url portal.views.add_comment post.id %}" method="POST">{% csrf_token %}
    <div id="cform">
        Name: {{ form.author }}
        <p>{{ form.body|linebreaks }}</p>
    </div>
    <div id="submit"><input type="submit" value="Submit"></div>
</form>

{% endblock %}